#cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-amplifier
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-client
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-clientside
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-common
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-docs
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-hrdag
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-jar-verifier
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-js-xml-generator
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-logi
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-meta
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-mspa
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-server
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-swing
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-thirdparty
cvs -d :ext:cvs.benetech.org:/var/local/cvs checkout martus-utils
